[package]
name = "rust_rdbms"
version = "0.1.0"
authors = ["shohei kondo <s.kondo1015@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
